package com.example.dell.pandalive.greendaoutils;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dell.pandalive.greendaoform.HistoryDatabase;
import com.example.dell.pandalive.greendaoform.MyDatabases;

import com.example.dell.pandalive.greendaoutils.HistoryDatabaseDao;
import com.example.dell.pandalive.greendaoutils.MyDatabasesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyDatabaseDaoConfig;
    private final DaoConfig myDatabasesDaoConfig;

    private final HistoryDatabaseDao historyDatabaseDao;
    private final MyDatabasesDao myDatabasesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyDatabaseDaoConfig = daoConfigMap.get(HistoryDatabaseDao.class).clone();
        historyDatabaseDaoConfig.initIdentityScope(type);

        myDatabasesDaoConfig = daoConfigMap.get(MyDatabasesDao.class).clone();
        myDatabasesDaoConfig.initIdentityScope(type);

        historyDatabaseDao = new HistoryDatabaseDao(historyDatabaseDaoConfig, this);
        myDatabasesDao = new MyDatabasesDao(myDatabasesDaoConfig, this);

        registerDao(HistoryDatabase.class, historyDatabaseDao);
        registerDao(MyDatabases.class, myDatabasesDao);
    }
    
    public void clear() {
        historyDatabaseDaoConfig.getIdentityScope().clear();
        myDatabasesDaoConfig.getIdentityScope().clear();
    }

    public HistoryDatabaseDao getHistoryDatabaseDao() {
        return historyDatabaseDao;
    }

    public MyDatabasesDao getMyDatabasesDao() {
        return myDatabasesDao;
    }

}
