package com.example.dell.pandalive.greendaoutils;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dell.pandalive.greendaoform.HistoryDatabase;

import com.example.dell.pandalive.greendaoutils.HistoryDatabaseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyDatabaseDaoConfig;

    private final HistoryDatabaseDao historyDatabaseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyDatabaseDaoConfig = daoConfigMap.get(HistoryDatabaseDao.class).clone();
        historyDatabaseDaoConfig.initIdentityScope(type);

        historyDatabaseDao = new HistoryDatabaseDao(historyDatabaseDaoConfig, this);

        registerDao(HistoryDatabase.class, historyDatabaseDao);
    }
    
    public void clear() {
        historyDatabaseDaoConfig.getIdentityScope().clear();
    }

    public HistoryDatabaseDao getHistoryDatabaseDao() {
        return historyDatabaseDao;
    }

}
